name: CCV2 Build Test

on:
  workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: print current date and time
        run: echo $(date +%F_%H-%M-%S)
      - name: Setup node 20.12.2
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Node version
        run: node --version
      - run : npm install
